/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../Library/Android/sdk/ndk/20.1.5948944/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/jni.h"
/* Header for class com_phuket_tour_studio_Mp3Encoder */

#ifndef _Included_com_phuket_tour_studio_Mp3Encoder
#define _Included_com_phuket_tour_studio_Mp3Encoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phuket_tour_studio_Mp3Encoder
 * Method:    encode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_phuket_tour_studio_Mp3Encoder_encode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
